# Generated by Django 5.1.2 on 2024-11-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
