# Generated by Django 5.1.4 on 2025-01-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_username_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
