# Generated by Django 5.1.2 on 2024-11-05 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatar/'),
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('category', models.CharField(default='', max_length=255)),
                ('time', models.DurationField()),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/cover/')),
                ('style', models.CharField(default='', max_length=255)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/cover/')),
                ('description', models.TextField()),
                ('compositions', models.ManyToManyField(blank=True, to='core.composition')),
            ],
        ),
        migrations.AddField(
            model_name='composition',
            name='playlist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.playlist'),
        ),
    ]
