# Generated by Django 5.1.2 on 2024-11-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_avatar_composition_playlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_listening', models.DateTimeField(auto_now_add=True)),
                ('compositions', models.ManyToManyField(blank=True, to='core.composition')),
            ],
        ),
    ]
