# Generated by Django 5.1.4 on 2025-01-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_max_otp_try_user_otp_user_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='category',
            field=models.CharField(default='', max_length=12),
        ),
    ]
