# Generated by Django 5.1.4 on 2025-01-08 09:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_composition_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='category',
            field=models.CharField(default='', max_length=12, validators=[core.models.validate_single_word]),
        ),
    ]
