# Generated by Django 5.1.4 on 2025-01-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_composition_name_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
