# Generated by Django 5.1.4 on 2025-01-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_composition_name_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_avatar.png', upload_to='images/avatar/'),
        ),
    ]
