# Generated by Django 5.1.4 on 2025-01-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='playlist_id',
        ),
        migrations.AddField(
            model_name='composition',
            name='playlist_id',
            field=models.ManyToManyField(blank=True, to='core.playlist'),
        ),
    ]
