# Generated by Django 5.1.4 on 2025-01-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar/default_avatar.png', upload_to='images/avatar/'),
        ),
    ]
