# Generated by Django 5.1.4 on 2025-01-23 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='time',
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='compostions',
            field=models.ManyToManyField(blank=True, to='core.composition'),
        ),
        migrations.AddField(
            model_name='user',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='core.playlist'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
