# Generated by Django 5.1.4 on 2025-01-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_composition_time_playlist_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='compostions',
            new_name='compositions',
        ),
    ]
