# Generated by Django 5.1.4 on 2025-01-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/images/avatar/default_avatar.png', upload_to='media/images/avatar/'),
        ),
    ]
