# Generated by Django 5.1.4 on 2025-01-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='image',
            field=models.ImageField(blank=True, default='images/cover/default_composition.png', upload_to='images/cover/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, default='images/cover/default_playlist.png', upload_to='images/cover/'),
        ),
    ]
